In [3]:
## Ejercicio 1

lista1 = []
a = (input("Introduce una secuencia de caracteres: "))
for e in a:
    lista1.append(e)
lista1.reverse()
print(lista1)


Introduce una secuencia de caracteres: 12345
['5', '4', '3', '2', '1']


In [4]:
## Ejercicio 2
s1 = input("Introduce el string 1: ")
s2 = input("Introduce el string 2: ")
l2 = []
if len(s1) == len(s2):
    for e in range(len(s1)):
        l2.append(s1[e])
        l2.append(s2[e])
else:
    print("Los strings no tienen la misma longitud")

for i in l2:
    print(i, end = "")
        

Introduce el string 1: hola
Introduce el string 2: bais
hboalias

In [2]:
## Ejercicio 3
e3s = str(input("Introduce un string: "))
e3s = e3s.lower()
e3cons = []
vocals =["a","e","i","o","u"]

for e in e3s:
    if e != "a" and e != "e" and e != "i" and e != "o" and e != "u" and e != " ":
        e3cons.append(e)
print(e3cons)
        
    

Introduce un string: hola
['h', 'l']


In [6]:
## Ejercicio 4
e4 = str(input("Introduce una palabra: "))
l4 = []
for e in e4:
    l4.append(e)
if l4 == l4[::-1]:
    print("La palabra es un palindromo.")
else:
    print("No es un palindromo.")

Introduce una palabra: hola
No es un palindromo.


In [8]:
## Ejercicio 5
import numpy as np
e5 = []
for i in range(3):
    e5.append([])
    for j in range(3):
        e5[i].append(float(input("Introduce el elemento ({},{})".format(i,j))))
print(e5)

for i in range(3):
    e5[i].sort(reverse = True)
    print("El maximo de la fila es {} es {}.".format(i, e5[i][0]))

Introduce el elemento (0,0)1
Introduce el elemento (0,1)2
Introduce el elemento (0,2)3
Introduce el elemento (1,0)4
Introduce el elemento (1,1)5
Introduce el elemento (1,2)6
Introduce el elemento (2,0)7
Introduce el elemento (2,1)8
Introduce el elemento (2,2)9
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
El maximo de la fila es 0 es 3.0.
El maximo de la fila es 1 es 6.0.
El maximo de la fila es 2 es 9.0.


In [15]:
## Ejercicio 6
e6 = int(input("Introduce un entero: "))
e6m = []

for i in range(e6):
    e6m.append([])
    for j in range(e6):
        e6m[i].append(e6 * i + j)

for i in range(e6):
    print(e6m[i])

Introduce un entero: 5
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]
[20, 21, 22, 23, 24]


In [37]:
## Ejercicio 7
import numpy as np
filas = int(input("Introduce el numero de filas: "))
col = int(input("Introduce el numero de columnas: "))

e7 = []

for i in range(filas):
    e7.append([])
    for j in range(col):
        e7[i].append(float(input("Introduce el elemento ({},{})".format(i,j))))
for i in e7:
    print(i)

sumas = []    
for j in range(col):
    suma = 0
    for i in range(filas):
        suma += e7[i][j]
    sumas.append(suma)

sumiguales = True
for i in range(col - 1):
    if sumas[i] != sumas[i-1]:
        sumiguales = False

if sumiguales == False:
    print("Las sumas de las columnas es distinta")
else:
    print("Las sumas de las columnas es igual.")
    
print(sumiguales)
print(sumas)

Introduce el numero de filas: 2
Introduce el numero de columnas: 2
Introduce el elemento (0,0)1
Introduce el elemento (0,1)1
Introduce el elemento (1,0)1
Introduce el elemento (1,1)1
[1.0, 1.0]
[1.0, 1.0]
Las sumas de las columnas es igual.
True
[2.0, 2.0]


In [47]:
## Ejercicio 8
import numpy as np
filas = int(input("Introduce el numero de filas: "))
col = int(input("Introduce el numero de columnas: "))

e8 = []
e8_iden = np.identity(col)
for i in range(filas):
    e8.append([])
    for j in range(col):
        e8[i].append(float(input("Introduce el elemento ({},{})".format(i,j))))
for i in e8:
    print(i)
    
if filas == col:
    if (e8 == e8_iden).all():
        print("La matriz es una matriz identidad!")
    else:
        print("La matriz introducida no es una matriz identidad.")
else:
    print("La matriz introducida no es cuadrada.")

Introduce el numero de filas: 2
Introduce el numero de columnas: 2
Introduce el elemento (0,0)1
Introduce el elemento (0,1)0
Introduce el elemento (1,0)0
Introduce el elemento (1,1)1
[1.0, 0.0]
[0.0, 1.0]
La matriz es una matriz identidad!


In [52]:
## Ejercicio 9
import numpy as np
filas = int(input("Introduce el numero de filas: "))
col = int(input("Introduce el numero de columnas: "))

e9 = []
e9_iden = np.identity(col)
for i in range(filas):
    e9.append([])
    for j in range(col):
        e9[i].append(float(input("Introduce el elemento ({},{})".format(i,j))))
for i in e9:
    print(i)

print("La matriz transpuesta es: \t")    
e9_t = np.transpose(e9)
for i in e9_t:
    print(i)

Introduce el numero de filas: 2
Introduce el numero de columnas: 2
Introduce el elemento (0,0)5
Introduce el elemento (0,1)4
Introduce el elemento (1,0)6
Introduce el elemento (1,1)2
[5.0, 4.0]
[6.0, 2.0]
La matriz transpuesta es: 	
[5. 6.]
[4. 2.]


In [53]:
## Ejercicio 10
import numpy as np
dim = int(input("Introduce la dimension de la matriz identidad a construir: "))
e10 = np.identity(dim)

for i in e10:
    print(i)

Introduce la dimension de la matriz identidad a construir: 5
[1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
[0. 0. 0. 1. 0.]
[0. 0. 0. 0. 1.]
